- name: install and run nginx
  host: web
  become: yes # equal to -b in adhocc command and getting root access
  tasks: given all tasks
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
