- name: variables
  hosts: localhost
  vars:
    course: AWS and Devops
    trainer: siva
    duration: 120hrs
  tasks:
  - name: print information
    ansible.builtin.debug:
      msg: "I learning {{course}} from trainer {{trainer}} duration {{duration}}."