- name: variables from files
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: please enter username
    private: false
  - name: PASSWORD
    prompt: Please enter password
    private: true  
  tasks:
  - name: print subject
    ansible.builtin.debug:
      msg: "Please enter {{USERNAME}} and password {{PASSWORD}}."