- name: data types
  hosts: web
  vars:
    course: Devops with Aws #string
    Tools: #list
    - linux
    - Shell
    - Ansible
    Experience: #map or dictionary
      DevOps: 3 #number
      AWS: 2
      Docker: 1
  tasks: 
  - name: print the variables
    ansible.builtin.debug:
      msg: "Course: {{course}} Tools: {{Tools}}, Experience is: {{Experience}}."