- name: dafult value
  hosts: localhost
  tasks:
  - name: print dafult value 
    ansible.builtin.debug:
      msg: "Hello {{course | default('Ansible') }}"

- name: upper case
  hosts: localhost
  vars:
    greeting: "Hello Good mroning"
  tasks:
  - name: convert into upper case
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"

- name: lower case
  hosts: localhost
  vars:
    greeting: "Hello Good mroning"
  tasks:
  - name: convert into lower case
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}"

- name: remove duplicates
  hosts: localhost
  vars:
    numbers: [ 1,2,2,3,4,4,5 ]
  tasks:
  - name: remove duplicates
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"

- name: print min and max ages
  hosts: localhost
  vars:
    ages: [ 25,35,65,75 ]
  tasks:
  - name: print min and max
    ansible.builtin.debug:
      msg: "min ages: {{ ages | min }} and max ages: {{ ages | max }}"

- name: convert dictionary into items/list
  hosts: localhost
  vars:
    my_dict: # this is called as dictionary or map or key/value pairs
      course: Ansible
      trainer: siva
      duration: 120hrs
  tasks:
  - name: before convert
    ansible.builtin.debug:
      msg: "Before convert: {{ my_dict }}"
  - name: after convert
    ansible.builtin.debug:
      msg: "After convert: {{ my_dict | dict2items }}"


- name: convert items to dictionary
  hosts: localhost
  vars:
    my_list:
    - {'key': 'course', 'value': 'Ansible'}
    - {'key': 'trainer', 'value': 'siva'}
    - {'key': 'duration', 'value': '120hrs'}
  tasks: 
  - name: convert items to dictionary
    ansible.builtin.debug:
      msg: "Before converting: {{ my_list }}"
  - name: convert items to dictionary
    ansible.builtin.debug:
      msg: "After converting: {{ my_list | items2dict }}"