- name: dafult value
  hosts: localhost
  tasks:
  - name: print dafult value 
    ansible.builtin.debug:
      msg: "Hello {{course | default('Ansible') }}"

- name: upper case
  hosts: localhost
  vars:
    greeting: "Hello Good mroning"
  tasks:
  - name: convert into upper case
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"
      